### ISSUE TITLE
Request for Access to Training Data

### ISSUE THREAD

**Issue by gabrielbianchin** [QuanEvans/InterLabelGO#1]
Hi @QuanEvans,

Thank you for sharing this project and providing the model. However, I encountered an issue while trying to access the training data in the link of README.md file. Could you please provide access to the training data or share a link where it can be downloaded?

Thank you in advance for your assistance.

**Comment by QuanEvans** [comment]
Hi @gabrielbianchin 

I've reuploaded the file. Could you please check the link again and let me know if you're able to access the training data now?

[https://seq2fun.dcmb.med.umich.edu/InterLabelGO/InterLabelGO+.tar.xz](https://seq2fun.dcmb.med.umich.edu/InterLabelGO/InterLabelGO+.tar.xz)

Thanks for your patience!

**Comment by gabrielbianchin** [comment]
Hi @QuanEvans,

Thank you for reuploading the file. I was able to access the training data successfully.

I appreciate your quick assistance!
